### ISSUE TITLE
Parse error: syntax error, unexpected token "::", expecting "(" on line 322

### ISSUE THREAD

**Issue by dzg** [johngodley/search-regex#101]
Loved this plugin on previous site.... but just installed on new WordPress 5.8.1 running Blocksy theme on PHP 8:

```
Parse error: syntax error, unexpected token "::", expecting "(" in /home/zgilad/2021.shellyshumblekitchen.com/wp-content/plugins/search-regex/models/search.php on line 322
```

Any fix? Thanks!

**Comment by johngodley** [comment]
The plugin does not support PHP 8. You will need to use the beta version: https://github.com/johngodley/search-regex/releases/tag/3.0-beta

**Comment by dzg** [comment]
Thank you!
