### ISSUE TITLE
Regex replacement not working

### ISSUE THREAD

**Issue by rekkerdblog** [johngodley/search-regex#103]
I use Modify Matches on column Content to search and replace regex. The search finds matches and the replace says it's replacing, but the actual content is not replaced at all.

![searchregex3](https://user-images.githubusercontent.com/91539581/135083107-76fe50c7-998c-4c23-bd03-b1885216b106.png)

Using PHP 8.0.11. Any idea what could be the problem?

**Comment by johngodley** [comment]
I've released beta 2 which should help.

https://github.com/johngodley/search-regex/releases/tag/3.0-beta

If you are using a global search you can do a global replace, which makes it a bit simpler than duplicating the search.
