### ISSUE TITLE
Parse error: syntax error, unexpected token "::", expecting "(" in /var/www/html/wp-content/plugins/search-regex/models/search.php on line 322

### ISSUE THREAD

**Issue by geeknotnerd** [johngodley/search-regex#105]
### Summary

Getting this error while activating the plugin and it fails to  be activated
Parse error: syntax error, unexpected token "::", expecting "(" in /var/www/html/wp-content/plugins/search-regex/models/search.php on line 322

Plugin version : 2.4.1
PHP version: PHP 8.0.10
Wordpress version: 5.8.1

**Comment by johngodley** [comment]
That version doesn't work with PHP 8. You will need to use the 3.0 beta

https://github.com/johngodley/search-regex/releases/tag/3.0-beta
