### ISSUE TITLE
This does not appear to work with php 8

### ISSUE THREAD

**Issue by garpinc** [johngodley/search-regex#107]
I upgraded to php 8 from 7 (where it was working) and I had to enter recovery mode and deactivate this plugin in order to get to admin console

**Comment by garpinc** [comment]
Plugin could not be activated because it triggered a fatal error.

Parse error: syntax error, unexpected token "::", expecting "(" in /home/dh_g8crkf/sapphire.dreamhosters.com/wp-content/plugins/search-regex/models/search.php on line 322

**Comment by garpinc** [comment]
I'm on WordPress 5.8.2

**Comment by johngodley** [comment]
You need to use the beta:

https://github.com/johngodley/search-regex/releases/tag/3.0-beta

**Comment by garpinc** [comment]
When will it be released?

**Comment by johngodley** [comment]
The beta is already released. I cannot say when the beta will become a final release.
