### ISSUE TITLE
Still supported? PHP8?

### ISSUE THREAD

**Issue by pstonge** [johngodley/search-regex#108]
Is this plugin still supported? The wordpress page says it hasn't been tested with the last few versions. I also get an error using PHP 8 in the following file.

search-regex/models/search.php line 322
$contexts = Match::get_all( $this->search, $source->get_flags(), $replacement, $row[ $column ] );

**Comment by johngodley** [comment]
Yes it's still supported - why would it not be?

You can use the beta version here:

https://github.com/johngodley/search-regex/releases/tag/3.0-beta
