### ISSUE TITLE
Incorrect SQL query parameters for wp_posts table

### ISSUE THREAD

**Issue by RemiliaDevil** [johngodley/search-regex#109]
## Summary
I found that "exclude drafts" SQL query not working correctly. More specifically, 
`where post_type='post' OR post_type='page' AND post_status != 'draft'` is not identical to `where (post_type='post' OR post_type='page') AND post_status != 'draft'`.
## How to reproduce
At least in my site, function "exclude drafts" is not working correctly. There are always many draft posts included.
## Extra recommendation
Is it possible to add an extra option "exclude trash" to exclude deleted items?

**Comment by johngodley** [comment]
Please use the beta version: https://github.com/johngodley/search-regex/releases/tag/3.0-beta
