### ISSUE TITLE
Problems with new verion

### ISSUE THREAD

**Issue by chaostica** [johngodley/search-regex#11]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

I'm trying to do a regex search and replace.
I'm searching for the following: 
**<span style="font-size: 14pt;">([^<]*)</span>**
I'm replacing with:
**\1**
I'm consistently getting the following error message.

> Plugin: 2.0
> WordPress: 5.4.1 (single)
> PHP: 7.3.1
> Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
> JavaScript: https://solarstuff.dev.cc/wp-content/plugins/search-regex/search-regex.js
> REST API: https://solarstuff.dev.cc/wp-json/
> Buster: 2.0 === 2.0
> 
> TypeError: Cannot read property 'indexOf' of undefined
> 
>     in Ea
>     in div
>     in div
>     in a
>     in f
>     in div
>     in a
>     in f
>     in StrictMode
>     in H
>     in ji

Also, the search would only crawl along at 2-3% per second (3500 post records) before returning the error.

_Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do:_
This has worked in the old version.  I'd pretty much stopped using it because of it's age and the way wordpress was reporting it as a serious problem.  Really happy that you're back.  Once I can get it working I'll add to your coffers.  Search Regex is one of the most useful plugins on the planet - none of the the other search and replace apps come close. 

### Actual Behavior
End result is I can't seem to run a regex search and replace.

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

As above

### Environment

**Please list your browser, browser version, version of WordPress and Search Regex plugin.**
Brave browser v1.8.9.5., Wordpress v5.4.1, Search Regex v2.
I'm running locally on a DesktopServer site.

**Comment by johngodley** [comment]
Yes, the search will be a bit slower because it's not trying to do your entire database in one go. This will mean that it also won't run out of memory or time out, and can be used on much larger data sets.

I've not been able to reproduce the above problem. Could you open your browser developer console and when the error occurs, see what the last request was in the Network tab and, if possible, right click and copy the response.

If you could send that to me then I'll be able to see what was returned on your site and why that might cause the error.

**Comment by johngodley** [comment]
Also, could you try https://github.com/johngodley/search-regex/releases/tag/2.0.1 and see if that changes anything

**Comment by chaostica** [comment]
Hi John,
I just updated to 2.0.1 and tried again.  It worked first time.  Whatever it was seems to be working now.  Thanks for your quick reply.  
One thought I had about a helpful feature would be to keep recent searches in a dropdown menu. I often use similar regex phrases and it would be helpful to restore a recent search/replace pair to modify rather than write something new.
Thanks for your work.

**Comment by johngodley** [comment]
Great! Thanks for letting me know.

Yep, I'd like to add some kind of stored phrases, and even some pre-defined ones for popular searches.
