### ISSUE TITLE
Error with PHP 8.0

### ISSUE THREAD

**Issue by Jon-Stout** [johngodley/search-regex#110]
Plugin yields error in WP 7.4 running PHP 8.0

Here is the error (you get this when activating the plugin): Parse error: syntax error, unexpected token "::", expecting "(" in /nas/content/live/scifidev/wp-content/plugins/search-regex/models/search.php on line 322

Running on a WPE dev site with WP 7.4 and PHP 8.0

**Comment by johngodley** [comment]
The latest WP is 5.8.2 (https://wordpress.org/download/).

You will need to use the beta for PHP 8:

https://github.com/johngodley/search-regex/releases/tag/3.0-beta
