### ISSUE TITLE
Error when changing from PHP 7.4.5 to PHP 8.1.2

### ISSUE THREAD

**Issue by PlanetThoughts** [johngodley/search-regex#114]
The plugin is not able to work with PHP 8.1.2 and/or with WordPress 5.9. On one site, I already had the plugin running under PHP 7.4.5, and when I changed to PHP 8.1.2 via control panel, Search Regex prevented logging in as admin for the WordPress site.

I deleted the plugin, and now tried re-installing it. That spun endlessly, and when I refreshed the page I could try to Activate, but that also spun endlessly.

Will there be a new version compatiable with PHP 8.x and with WordPress 5.9? Thank you, don't want to lose this excellent plugin.

**Comment by johngodley** [comment]
You can use the beta version here:

https://github.com/johngodley/search-regex/releases/tag/3.0-beta
