### ISSUE TITLE
Issue: Replace All button not working for 3.0 Beta 3

### ISSUE THREAD

**Issue by SJNBham** [johngodley/search-regex#128]
### Summary
When attempting a Global Text Replace action, the Replace All button doesn't work.

### Environment

Using Edge (Chromium) on Windows 10 in WordPress 6 and Search Regex 3.0-beta-3 hosted on WPEngine.com. We also disabled all plugins and activated a TwentyTwentyTwo default theme to try to rule out conflicts with other plugins. We tried PHP 7.4 and 8 with the same results. Also tried in FireFox 100.0.

**Comment by wpgaurav** [comment]
+1.

**Comment by johngodley** [comment]
Fixed in beta 4 https://github.com/johngodley/search-regex/releases/tag/3.0-beta

**Comment by SJNBham** [comment]
@johngodley - thank you for the update!
