### ISSUE TITLE
Issue: Regex doesn't appear to be working as expected in Beta 4

### ISSUE THREAD

**Issue by SJNBham** [johngodley/search-regex#134]
### Summary

Attempted a Global Text Replace operation using the following as the search value:

`<a\shref="\/documents\/.+">`

The Case and Regex flags were selected and the Source was Posts. 

The results were unexpected in that Title, Slug, and Content were marked as to be replaced. Whereas, if we just search without the Regex flag using the following, we get the expected results:

`/documents/`

### Environment

WordPress 6 and Search Regex 3 beta 4 in Edge (Chromium) with PHP 7.4. 

<img width="1001" alt="2022-07-13 15_00_39-Search Regex ‹ City of Bellingham — WordPress and 15 more pages - Steven (Work) " src="https://user-images.githubusercontent.com/11393597/178845017-5b60dd7a-8c64-4745-9132-1e224dfe9449.png">
<img width="658" alt="2022-07-13 15_00_05-regex101_ build, test, and debug regex and 9 more pages - Steven (Work) - Micros" src="https://user-images.githubusercontent.com/11393597/178845019-7b64a2e7-a092-4b15-beef-727db1057d4e.png">
<img width="1006" alt="2022-07-13 14_55_47-Search Regex ‹ City of Bellingham — WordPress and 15 more pages - Steven (Work) " src="https://user-images.githubusercontent.com/11393597/178845022-cd3d9d8b-15b2-4838-b777-060366e06958.png">

**Comment by SJNBham** [comment]
To simplify things, just searching on "\/documents\/" and using the Regex flag results in unexpected results unless we're not understanding the regex syntax the plugin is expecting.

<img width="989" alt="2022-07-13 15_17_42-Search Regex ‹ City of Bellingham — WordPress and 12 more pages - Steven (Work) " src="https://user-images.githubusercontent.com/11393597/178846538-759e4c85-2bec-4ebf-ac19-7c64fd35cb49.png">

**Comment by johngodley** [comment]
Fixed in beta 5 - the regex was incorrectly making it replace the whole column, not just the match.

https://github.com/johngodley/search-regex/releases/tag/3.0-beta

Side note - you don't need to escape the slashes, and it's fine to put spaces in the expression. You can press the ellipsis button in regex101 and change the delimiter to something else.
