### ISSUE TITLE
pagination appears to not be working in regex returned results

### ISSUE THREAD

**Issue by harwooje** [johngodley/search-regex#146]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

pagination for Search results not working

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

Just doing a text search

Explain what actually happened. If suggesting a new feature then explain what currently happens.

I search my site for a common text bit, like "Transcript:" and have the "25 results per page" option selected. After the search there are 25 results on page 1, but the page navigation buttons only show "page 1 of 1." If I select the "500 results per page" I get 500 results on page 1 but still "page 1 of 1" at the bottom. (There should be several thousand returns.)

Please list your browser, browser version, version of WordPress and Search Regex plugin.

Firefox 91.13.0esr (64-bit)
WP 6.0.2
regex version 3.0.5

<img width="710" alt="results page bottom" src="https://user-images.githubusercontent.com/2712039/188213954-412d302e-1e9e-478d-8b42-1be381588347.png">
<img width="1128" alt="search setup" src="https://user-images.githubusercontent.com/2712039/188213955-c6c590cc-ec21-45a6-8834-9cdadc05d2f7.png">

**Comment by johngodley** [comment]
Yes, this is a known problem and will be fixed soon.
