### ISSUE TITLE
Count of search results unexpectedly changes when regex flag set

### ISSUE THREAD

**Issue by xjamesb** [johngodley/search-regex#150]
### Summary

I expect that when searching for a string such as 

formidable id

I will get the same number of search results with the regex flag present and absent

### Actual Behaviour

Actually I get 60 results when the regex flag is not present and 25 results when it is present.

### Steps to reproduce

[Screenshot](https://1drv.ms/u/s!AkH38tr8tPdPmMVfBt1Pmw6IZUKqNA?e=tSugR6)

### Environment

Current

**Comment by xjamesb** [comment]
> When searching regex it will only tell you how many results it's found so far. You need to page through the database to know the total.

I have verified that changing the number of items per page increases the count to the expected number. 

I think that the difference in counts is a BUG and the issue should remain open. However it is your call!

Thanks for writing a brilliant plugin.

**Comment by johngodley** [comment]
That's how it is intended to work so I'll close this issue.
