### ISSUE TITLE
Exporting regex searches to CSV fails

### ISSUE THREAD

**Issue by xjamesb** [johngodley/search-regex#151]
### Summary

Exporting regex searches to CSV fails

### Actual Behaviour
I actually get a .csv containing the text 

```
[object Object]
[object Object]
```

### Steps to reproduce

1. search for a string for example "formidable id" in posts and pages with no flags and Action = "No action". Count the number of matches (60)
2. change the action to "Export Matches" with the format "CSV"
3. Click "Export Matches"
4. Verify that the CSV file contains 60 rows (see earlier bug report for missing header row).
5. Now change the search flag to Regex
6. Click "Export Matches"
7. I expect the CSV file to contain 60 rows, actually it contains the text [object Object]

[Screenshot](https://1drv.ms/u/s!AkH38tr8tPdPmMVjFosZisGM2g7j9Q?e=h7PuuP)

### Environment

Current

**Comment by mtbluedog** [comment]
Love this plugin and have been using it for years, but yes, exporting to CSV seems to be broken. I get an empty csv file with just [object Object] in it. Search parameters in screenshot. 
![regex pmg](https://github.com/user-attachments/assets/82ebb89a-ab97-4764-b782-926c6ff508c3)

**Comment by johngodley** [comment]
This will be fixed in the next version.

**Comment by mtbluedog** [comment]
Thanks!
