### ISSUE TITLE
Missing replacements?

### ISSUE THREAD

**Issue by roireshef** [johngodley/search-regex#16]
### Summary

I'm trying to replace some \<strong\> tags wrapping specific content with \<span\> tags instead. Using regex I was able to capture few occurrences in the posts table in my DB. When clicking replace all, the progress bar shows like it's working, everything finally terminates successfully, and when I search for this term again, I can't find it, which hints on that all of its occurrences have been replaced. 

The problem is, when I'm loading the pages (where replacements took place) again, I'm being showed with the content before replacement. I have taken down ALL cache layers, cleared them, etc.
Also, when I'm going into editing mode for my posts, here as well, I'm seeing the original content (like no replace took place). I'm using a pagebuilder (Elementor), but it shouldn't really be a problem IMHO since it uses the same *posts* table in the DB.

### Steps to reproduce

Search string: `(<em>)*(<strong>)[^<]*(sometext[^<]*)(<\/strong>)(<\/em>)*`
Replace: `<span class="tip_title">$3</span>`
Replace Flag: Single (not really sure what is that)
Source: Posts
Search Flags: IGNORE CASE, REGULAR EXPRESSION

### Environment

I'm using Chrome on Windows, a wordpress.org-based-site on shared hosting service.

**Comment by johngodley** [comment]
Can you give some examples, and maybe some URLs? If you edit the posts with the content does it still appear?

**Comment by roireshef** [comment]
Hi @johngodley - I just added search/replace strings above. When I'm editing manually with the replacement content, outside your plugin (in the pagebuilder) it updates successfully. Only when using search and replace (in your plugin) it doesn't seem to work well... On the other hand, once executed, if I hit search again, there will be 0 results.

**Comment by roireshef** [comment]
BTW, this is a URL example: https://www.yolo-blog.com/guatemala/
It's written in Hebrew, not sure how easy it would be for you to extract meaningful information out of it, but for any chance, it's here.

**Comment by johngodley** [comment]
Does the content exist when you edit the post in the WP editor after it has been replaced? Not Elementor, but the WP editor.

**Comment by roireshef** [comment]
I can't see visuals for posts edited with Elementor in WP Editor, but when looking in a code-mode, I see the newly replaced content. That said, it won't appear when page is loaded, neither in elementor. What's going on? Do you have a clue?

**Comment by roireshef** [comment]
It appears to be related to https://github.com/elementor/elementor/issues/5179
It seems like your plugin is well-behaving, and that's Elementor's fault.

**Comment by johngodley** [comment]
Ok, thanks for checking and getting back with the information. If $pref_post_meta is the same as post meta then you can change the Source to post meta and it should be able to find the data there.

https://searchregex.com/support/search-source/

**Comment by juanmaguerrero** [comment]
@roireshef Yes I couldn't believe that either... it costed me a client sadly. I convinced the client to buy some elementor-based theme, plus the plugin, and then I could not use it for updating his already existing site due to this. I'll never use it again, currently I make react-based frontend with wordpress working as backend-only.

**Comment by johngodley** [comment]
I'm going to close this issue, but please reopen it if you have more details.
