### ISSUE TITLE
Replace Match with EMPTY Text

### ISSUE THREAD

**Issue by dbareis** [johngodley/search-regex#162]
It is not clear what "remove" (or "Multi" for that matter)  does for replacement text and the small FAQ doesn't say.  I was too scared to use it so I made the replacement text a single space (a non perfect solution).  I do not want to remove any database entries, I just want text replacement.

The "Replace All" button will not be ungreyed if the Replacement text is Empty (what I want to use as the replacement.

**Comment by johngodley** [comment]
Remove removes the text, multi is multiline.

Removing entire entries is made very explicit.

**Comment by dbareis** [comment]
A thinking person might ask themselves how explicit it actually is if someone needs to ask.  If you don't want feedback just say so.

**Comment by johngodley** [comment]
> If you don't want feedback just say so.

I'm not sure why you added that, but ok.

Remove will remove the matched text. It comes under the Global Text Replace action. Selecting this changes disables the replace input. Picking 'multi' will immediately show a multiline input.

To delete an entry you use the Delete Matches action.
