### ISSUE TITLE
Delete String between Begins AND Ends

### ISSUE THREAD

**Issue by Bullitt1968** [johngodley/search-regex#169]
Hello,

I would like to delete a multi-line content. Each content starts with <span class="info">[tooltip tip=".

and ends with:

"] to the glossary.

The content is always different. Here are two examples:

<span class="info">[tooltip tip="Buddhism is a teaching tradition and religion that finds its origin in India. It has about 377 million followers worldwide - the information varies depending on the source between 230 and 500 million believers - and is thus the fourth largest religion on earth ... go to glossary"]

<span class="info">[tooltip tip="ACT was developed by psychologist Steven Hayes and his colleagues Kelly Wilson and Kirk Strosahl. ACT is one of the newer behavioral therapies, the so-called "third wave," ... go to glossary"]

Translated with www.DeepL.com/Translator (free version)

Kind regards

Mark

**Comment by johngodley** [comment]
Ok. The support site has all the information you need:

https://searchregex.com/support/

Particularly around regular expressions
