### ISSUE TITLE
redirect brakes plugin

### ISSUE THREAD

**Issue by kocjs** [johngodley/search-regex#171]
I have redirect to remove trailing slash on the end of file in .htaccess, prevents the plugin form working.  I would expect the plugin to work anyway.

**Comment by johngodley** [comment]
You will need to provide more information. Break the plugin how?

**Comment by kocjs** [comment]
Sure, sorry. I am unable to upload a screen shot.

`It says: Your wordpress rest API is returning a 404 page. This is almost certainly  an external plugin or server configuration issue. 

You will will need to fix this on your site. Redirection is not causing this error.`

However it is definitely the redirection, as if i revert it, it works as expected. This is how i set up the redirect.

`<IfModule mod_rewrite.c>
#Turn on Rewrite Engine
RewriteEngine On

#Remove trailing slash from non-filepath urls
RewriteCond %{REQUEST_URI} /(.+)/$
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ https://example.com/%1 [R=301,L]

#Include trailing slash on directory 
RewriteCond %{REQUEST_URI} !(.+)/$
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^(.+)$ https://example.com/$1/ [R=301,L]

#Force HTTPS and remove WWW
RewriteCond %{HTTP_HOST} ^www\.(.*)$ [OR,NC]
RewriteCond %{https} off  
RewriteRule ^(.*)$ https://example.com/$1 [R=301,L]
</IfModule>`

**Comment by kocjs** [comment]
Ok, i have managed to update my rules. And it is working now. This is all new to me.
It looks like my redirection did prevent your plugin to access the access the rest api.

# Remove trailing slash from non-filepath urls
RewriteCond %{REQUEST_URI} /(.+)/$
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !^/wp-json/ [NC]
RewriteRule ^ https://example.com/%1 [R=301,L]

# Include trailing slash on directory 
RewriteCond %{REQUEST_URI} !(.+)/$
RewriteCond %{REQUEST_FILENAME} -d
RewriteCond %{REQUEST_URI} !^/wp-json/ [NC]
RewriteRule ^(.+)$ https://example.com/$1/ [R=301,L]

Unfortunately it seams that someone needs to remove the trailing slash at the end of a post link my first rule set is recommended as good praxis, also my hoster has given my thumps up for it.

**Comment by kocjs** [comment]
I am opening this again, just in the hope to get answers on this questions.
Feel free to close it.

**Comment by johngodley** [comment]
WordPress, by default, will add a trailing slash. It makes no real difference whether you have one or not, so I wouldn't worry about it and just go with the default.
