### ISSUE TITLE
How to exclude Images?

### ISSUE THREAD

**Issue by frmenu** [johngodley/search-regex#174]
I want to replace year from 2023 to 2024 in my titles, metas, content and Article schemas of 700 posts with just one click.

But the problem I face is that 2023 is also present in Image URLS, 
![image](https://github.com/johngodley/search-regex/assets/155574109/bd70496d-c5aa-4a77-9812-fd95ef1ff497)

which after changed will break thee images on my [site](https://frmenu.org/).

is there any way or which filter I should use and how that only searched 2023 from titles, metas, content and Article schemas only and do not include images or URLs because image URLs are URLs as well. I also applied sluyg fil;ter and excluded media but it still searched the image URLS.

Need your help.

**Comment by johngodley** [comment]
You can use a regular expression that matches 2023 only when not surrounded by a slash.
