### ISSUE TITLE
I wonder if it accepts ^ and $ in regular expressions?

### ISSUE THREAD

**Issue by dejudicibus** [johngodley/search-regex#178]
I tried to look for all occurences of </a> that are on a single line, that is
```
Fred
</a>
George
```
but not 
```
Fred</a>
George
```
or 
```
Fred
</a>George
```

So I used
```
^</a>$
```
but found no occurencesin posts, even if they exists. Any idea why?

**Comment by johngodley** [comment]
I can't tell you why it didn't find any occurences. If the expressions matches then it will return results, otherwise it won't. This must mean your expression doesn't match.
