### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by ahangarha** [johngodley/search-regex#2]
This is the issue reported on [Wordpress](https://wordpress.org/support/topic/blank-page-145) as well.
As far as I traced the problem, it is related to the cases of searching and replacing big number of matching terms (in my case usually more than 200). In such cases, the error (which not shown on server side usually) is something like this:
`( ! ) Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 461727 bytes) in C:\wamp\www\******\wp-content\plugins\search-regex\models\search.php on line 188`

As the existing codes cannot handle this issue automatically, it needs to be done manually by limiting the number of search and replace. But for some reason which is not known to me, limit functionality is not working.
Therefore, people get error/blank page by running the plugin.

**Comment by johngodley** [comment]
Closing as no longer relevant with version 2.0. Thanks for the report.
