### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by nathanmerryInvestoo** [johngodley/search-regex#23]
Hi, 

on one of my sites, where I have a previous version of your plugin installed, the plugin is working fine. But on another site I have the newer version and the search is not returning anything 

<img width="1274" alt="Screenshot 2020-06-16 at 16 39 57" src="https://user-images.githubusercontent.com/63409927/84795957-063e9d00-aff0-11ea-999b-afc449e50de1.png">

<img width="1269" alt="Screenshot 2020-06-16 at 16 40 42" src="https://user-images.githubusercontent.com/63409927/84796052-20787b00-aff0-11ea-9271-ba7968a54784.png">

If the way you have process your regex has changed, or otherwise, please let me know.

**Comment by nathanmerryInvestoo** [comment]
> Hi,
> 
> on one of my sites, where I have a previous version of your plugin installed, the plugin is working fine. But on another site I have the newer version and the search is not returning anything
> 
> <img alt="Screenshot 2020-06-16 at 16 39 57" width="1274" src="https://user-images.githubusercontent.com/63409927/84795957-063e9d00-aff0-11ea-999b-afc449e50de1.png">
> 
> <img alt="Screenshot 2020-06-16 at 16 40 42" width="1269" src="https://user-images.githubusercontent.com/63409927/84796052-20787b00-aff0-11ea-9271-ba7968a54784.png">
> 
> If the way you have process your regex has changed, or otherwise, please let me know.

**Comment by nathanmerryInvestoo** [comment]
> Hi,
> 
> on one of my sites, where I have a previous version of your plugin installed, the plugin is working fine. But on another site I have the newer version and the search is not returning anything
> 
> <img alt="Screenshot 2020-06-16 at 16 39 57" width="1274" src="https://user-images.githubusercontent.com/63409927/84795957-063e9d00-aff0-11ea-999b-afc449e50de1.png">
> 
> <img alt="Screenshot 2020-06-16 at 16 40 42" width="1269" src="https://user-images.githubusercontent.com/63409927/84796052-20787b00-aff0-11ea-9271-ba7968a54784.png">
> 
> If the way you have process your regex has changed, or otherwise, please let me know.

**Comment by nathanmerryInvestoo** [comment]
(i know for a fact that that string is in our content)

**Comment by johngodley** [comment]
You don't need to use a delimiter, and you don't need to use a regular expression - a standard search will work much faster.

**Comment by nathanmerryInvestoo** [comment]
thanks for the speedy response - works perfect now.
