### ISSUE TITLE
Search Regex Error: not found usermeta table in multiple site

### ISSUE THREAD

**Issue by senooken** [johngodley/search-regex#27]
```
Plugin: 2.1
WordPress: 5.4.2 (multi)
PHP: 7.4.3
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0
JavaScript: https://mtg.senooken.jp/wp-content/plugins/search-regex/search-regex.js
REST API: https://mtg.senooken.jp/wp-json/
Memory: 500M
Timeout: 300

Error: Table 'senooken_main.senooken_2_usermeta' doesn't exist (searchregex_database)
Action: search-regex/v1/search/ POST
Code: 500 Internal Server Error
Raw: {"code":"searchregex_database","message":"Table 'senooken_main.senooken_2_usermeta' doesn't exist","data":401}
```

Hi. I found this bug when I include user meta info in search target in my multiple sites.

**Comment by johngodley** [comment]
Does the table `senooken_main.senooken_2_usermeta` not exist on your installation?

**Comment by senooken** [comment]
Yes. There is no `senooken_main.senooken_2_usermeta` table (no `*usermeta*` table) from phpmyadmin.

Would you check this table before search for preventing error?

**Comment by johngodley** [comment]
This problem doesn't occur in the 3.0 beta:

https://github.com/johngodley/search-regex/releases/tag/3.0-beta
