### ISSUE TITLE
Apparent crash under WP 5.2.2

### ISSUE THREAD

**Issue by owenduffy** [johngodley/search-regex#4]
I get emails from WP notifying a problem, and it seems to happen when the search results are empty.

Error Details
=============
An error of type E_ERROR was caused in line 26 of the file /home/owenduffy/public_html/blog/wp-content/plugins/search-regex/view/results.php. Error message: Uncaught Error: Call to undefined method SearchRegex::base_url() in /home/owenduffy/public_html/blog/wp-content/plugins/search-regex/view/results.php:26
Stack trace:
#0 /home/owenduffy/public_html/blog/wp-content/plugins/search-regex/search-regex.php(130): include()
#1 /home/owenduffy/public_html/blog/wp-content/plugins/search-regex/search-regex.php(116): SearchRegex->render('results', Array)
#2 /home/owenduffy/public_html/blog/wp-includes/class-wp-hook.php(286): SearchRegex->admin_screen('')
#3 /home/owenduffy/public_html/blog/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#4 /home/owenduffy/public_html/blog/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#5 /home/owenduffy/public_html/blog/wp-admin/admin.php(253): do_action('tools_page_sear...')
#6 /home/owenduffy/public_html/blog/wp-admin/tools.php(10): require_once('/home/owenduffy...')
#7 {main}
  thrown

**Comment by owenduffy** [comment]
I uninstalled and reinstalled, and it seems to work without error now.

**Comment by owenduffy** [comment]
...but it returned quickly.

**Comment by owenduffy** [comment]
So I have deleted line 26 from results.php.

**Comment by johngodley** [comment]
Closing as no longer relevant with version 2.0. Thanks for the report.
