### ISSUE TITLE
rest_no_route

### ISSUE THREAD

**Issue by owenduffy** [johngodley/search-regex#41]
```
Plugin: 2.2.1
WordPress: 5.5 (single)
PHP: 7.4.8 256M 30s
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
JavaScript: https://owenduffy.net/blog/wp-content/plugins/search-regex/search-regex.js
REST API: https://owenduffy.net/blog/index.php?rest_route=/

Action: https://owenduffy.net/blog/index.php?rest_route=/search-regex/v1/search/ POST
Params: {"searchPhrase":"test","searchFlags":["case"],"source":["post","page"],"sourceFlags":[],"replacement":"","perPage":25,"page":0,"searchDirection":"forward"}
Code: 404 Not Found

Error: No route was found matching the URL and request method (rest_no_route)
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}

Action: https://owenduffy.net/blog/index.php?rest_route=/search-regex/v1/search/ POST
Params: {"searchPhrase":"test","searchFlags":["case"],"source":["post","page"],"sourceFlags":[],"replacement":"","perPage":25,"page":0,"searchDirection":"forward"}
Code: 404 Not Found

Error: No route was found matching the URL and request method (rest_no_route)
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

**Comment by owenduffy** [comment]
Yes, I saw that likely cause when the error presented first.

Search Regex was working (current version), and between when it worked and not,PHP was upgraded to v7.4.8 and IIRC Wordpress to v5.5. I am not aware of any security add-ins that would block the api.

I am prompted "Can you access your REST API without it redirecting? You will need to fix any errors." When I click the link, it appears to work, there is a huge formatted output and I do not know how to appraise it or whether it contains sensitive information (hence it is not attached).

Hope this helps John... Owen.

**Comment by johngodley** [comment]
Your REST API is publicly available, and I can access it myself. However, when the plugin tries to use it then it returns an error. The only thing that could do this is something running on your site. Caching may also affect things.

**Comment by owenduffy** [comment]
Ok, yes I could see that it was accessible... though unsure it it had the complete contents required.

I disabled a few add-ins that I thought might in some way restrict access, but to no avail.

The Wordpress is served on Godaddy hosting, so maybe they have implemented some magic.

Pity it is not working, thanks for your effort John.

Owen

**Comment by johngodley** [comment]
What does your site health say? It will likely have the same problem

**Comment by owenduffy** [comment]
The only issue with site health is:
 The optional module, zip, is not installed, or has been disabled.
No other problems.

**Comment by owenduffy** [comment]
This is the latest dump:

`Plugin: 2.3.2
WordPress: 5.5.1 (single)
PHP: 7.4.9 256M 30s
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
JavaScript: https://owenduffy.net/blog/wp-content/plugins/search-regex/search-regex.js
REST API: https://owenduffy.net/blog/index.php?rest_route=/
Query: ?page=search-regex.php&searchphrase=asdf
Buster: 2.3.2 === 2.3.2

TypeError: Cannot read property 'rootUrl' of undefined

    in ga
    in div
    in div
    in Qa
    in div
    in Ka
    in div
    in i
    in f
    in Zi
    in ba
    in div
    in ja
    in tu
    in div
    in u
    in Unknown
    in f
    in StrictMode
    in Le
    in Oc`

**Comment by johngodley** [comment]
Have you tried changing the REST API option? I just realised that you're not using the default one.

**Comment by owenduffy** [comment]
I am using the default, and the other two options fail.
![Screenshot-200914053158](https://user-images.githubusercontent.com/4297310/93026788-f749a400-f64b-11ea-8725-9b8372f0b8b3.png)

**Comment by owenduffy** [comment]
I just put another update on to v2.3.3 and it now works without any changes at this end.

**Comment by owenduffy** [comment]
Thanks John.
