### ISSUE TITLE
Search Regex Error

### ISSUE THREAD

**Issue by daisukike** [johngodley/search-regex#46]
Good evening!

My name is Daisuke.

I want to use your plugin, but I got an error.

I tried reloading the plugin but the results are the same.

I would like to know how to stop this error.
```
Plugin: 2.2.1
WordPress: 5.5 (single)
PHP: 7.2.29 256M 30s
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
JavaScript: https://torenndo-basuta.com/wp-content/plugins/search-regex/search-regex.js
REST API: https://torenndo-basuta.com/wp-json/

Error: Unexpected end of JSON input (SyntaxError)
```

**Comment by johngodley** [comment]
You can see the problem here:

https://torenndo-basuta.com/wp-json/

You will need to fix that error.

**Comment by daisukike** [comment]
I clicked the link, but the screen turned white and I couldn't find the problem.



----- Original Message -----

**Comment by johngodley** [comment]
Sure. Something is broken on your website and you will need to fix it. For reference, this is what it should look like:

https://redirection.me/wp-json/

This is not related to Redirection.

**Comment by daisukike** [comment]
I disabled WP External Links 2.46 in the plugin. Then the REST API was displayed.

And Search Regex worked fine.


Search Regex worked fine when I enabled a plugin other than WP External Links.



Thanks for your support.


※This is a plug-in that allows you to collectively manage settings related to links. (Automatic insertion of rel=”nofollow etc)

**Comment by johngodley** [comment]
Great. It might be worth contacting the owner of that plugin to see if they can fix the API issue.

**Comment by daisukike** [comment]
Thank you for your new advice.

Actually send a message for WP External Links Customer.

**Comment by daisukike** [comment]
When I tried to use Search Regex several times today, I got this error.↓

エラー詳細
===============
エラータイプ E_ERROR が /home/oregadaisuke/torenndo-basuta.com/public_html/wp-content/plugins/search-regex/search-regex-admin.php ファイルの 153 行目で発生しました。 エラーメッセージ: Uncaught Error: Cannot use object of type stdClass as array in /home/oregadaisuke/torenndo-basuta.com/public_html/wp-content/plugins/search-regex/search-regex-admin.php:153
Stack trace:
#0 /home/oregadaisuke/torenndo-basuta.com/public_html/wp-includes/class-wp-hook.php(287): Search_Regex_Admin->searchregex_head('')
#1 /home/oregadaisuke/torenndo-basuta.com/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#2 /home/oregadaisuke/torenndo-basuta.com/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home/oregadaisuke/torenndo-basuta.com/public_html/wp-admin/admin.php(237): do_action('load-tools_page...')
#4 /home/oregadaisuke/torenndo-basuta.com/public_html/wp-admin/tools.php(40): require_once('/home/oregadais...')
#5 {main}
  thrown


'plurals' => isset( $translations{'plural-forms'}) ? $translations{'plural-forms'}: 'nplurals=2; plural=n != 1;',is a problem, but I do not know how to solve it.

I don't know if it's a compatibility issue with the theme, but is there a solution?


My wordpress specs↓
WordPress バーション5.5.1
現在のテーマ: Cocoon Child (バージョン 1.1.2)
現在のプラグイン: Search Regex (バージョン 2.3)
PHP バージョン7.2.29

**Comment by johngodley** [comment]
Please try version 2.3.1

**Comment by daisukike** [comment]
Search Regex worked fine when you got the update.

Thank you for your support.
