### ISSUE TITLE
Problem starting Search Regex 2.3

### ISSUE THREAD

**Issue by periwiliam** [johngodley/search-regex#48]
```
Uncaught TypeError: Cannot read property 'remove' of null https://game.mangmoba.com/wp-content/plugins/search-regex/search-regex.js?ver=2.3-1042cf6450db9de5eb8e491f46fba548 2
```

Plugin: 2.3
WordPress: 5.5.1 (single)
PHP: 7.2.30-1+0~20200419.40+debian9~1.gbpb1b799 1024M 6000s
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
JavaScript: https://game.mangmoba.com/wp-content/plugins/search-regex/search-regex.js
REST API: https://game.mangmoba.com/wp-json/

**Comment by maboroshin** [comment]
Me too, on two site. (I'm Japanese translator)
```Uncaught Error: Cannot use object of type stdClass as array in /home/anysite/www/wp-content/plugins/search-regex/search-regex-admin.php:153 Stack trace: #0 /home/anysite/www/wp-includes/class-wp-hook.php(287): Search_Regex_Admin->searchregex_head('') #1 /home/anysite/www/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #2 /home/anysite/www/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /home/anysite/www/wp-admin/admin.php(237): do_action('load-tools_page...') #4 /home/anysite/www/wp-admin/tools.php(40): require_once('/home/anysite/ww...') #5 {main} thrown in /home/anysite/www/wp-content/plugins/search-regex/search-regex-admin.php on line 153```

Search Regex 2.3
PHP 7.3/7.4 (two site)
Browser: Chrome

**Comment by johngodley** [comment]
Please try version 2.3.1
