### ISSUE TITLE
Replace All not replacing all?

### ISSUE THREAD

**Issue by dzg** [johngodley/search-regex#53]
With this setup ...
![image](https://user-images.githubusercontent.com/466557/92525110-1b366100-f1d8-11ea-8869-ea4744cbad75.png)

I click 'Replace All' ... then 'Search' again ... and nothing has been done. Same results.

But if I Replace an individual row:
![image](https://user-images.githubusercontent.com/466557/92525232-5173e080-f1d8-11ea-8d6b-5346a53aaacc.png)
then it works on that row.

**Comment by johngodley** [comment]
Can you copy/paste the JSON preset?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
