### ISSUE TITLE
Can't load localization

### ISSUE THREAD

**Issue by maboroshin** [johngodley/search-regex#55]
This plugin is very popular in Japan!

ver2.3.2 now works. But, English is now loaded. ver2.3.0-2.3.1 loaded Japanese files.

In update history, "Fix locale pluralization throwing an error". Is this relevant?

The Japanese language does not have a plural entry field. In the .po file, the length of the array is 1.

```
msgid "Uploaded %(total)d preset"
msgid_plural "Uploaded %(total)d presets"
msgstr[0] "計%(total)d項目のプリセットをアップロードしました"
```

**Browser**: Current Chrome, Firefox

**Comment by johngodley** [comment]
Please try 2.3.3

**Comment by maboroshin** [comment]
It fixed.
