### ISSUE TITLE
Problem starting Search Regex 2.3

### ISSUE THREAD

**Issue by periwiliam** [johngodley/search-regex#58]
```
Uncaught TypeError: Cannot read property 'remove' of null https://drakor.mangmoba.com/wp-content/plugins/search-regex/search-regex.js?ver=2.3-1042cf6450db9de5eb8e491f46fba548 2
```

Plugin: 2.3
WordPress: 5.5.1 (single)
PHP: 7.2.30-1+0~20200419.40+debian9~1.gbpb1b799 1024M 6000s
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
JavaScript: https://drakor.mangmoba.com/wp-content/plugins/search-regex/search-regex.js
REST API: https://drakor.mangmoba.com/wp-json/

**Comment by johngodley** [comment]
Can you use the latest version?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
