### ISSUE TITLE
regular text replacement (without regex expression) discards '\' characters in articles

### ISSUE THREAD

**Issue by RemiliaDevil** [johngodley/search-regex#69]
### Summary

I find that this plugin discards all characters '\\' in the affected pages silently. All of my mathjax shortcodes are affected.

### Steps to reproduce

1. Create an article with regular texts containing '\\' characters.
2. Find and replace regular texts **that do not contain any**  '\\' characters.
3. Although I do nothing related with '\\' character, all the '\' characters disappear after the plugin's batch work

### Environment

Chrome; OSX; search regex 2.4 ; wordpress 5.5.3; php 7.4
I have already reproduced the steps in a new-installed wordpress 5.5.3 environment without any other plugins and themes.

**Comment by owenduffy** [comment]
This is a really damaging bug if you use latex math expressions, I have just spent hours fixing the results of this bug.
