### ISSUE TITLE
Problem starting Search Regex 2.3.3 on IE

### ISSUE THREAD

**Issue by rakutaro** [johngodley/search-regex#73]
A syntax error occurs on Internet Explorer 11.

```
構文エラーです。 https://chubusangaku.jp/wp-content/plugins/search-regex/search-regex.js?ver=2.3.3-a550313b93ff845a736292dd75b34ab8 2
```

Plugin: 2.3.3
WordPress: 5.4.2 (single)
PHP: 7.4.4 256M 180s
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
JavaScript: https://chubusangaku.jp/wp-content/plugins/search-regex/search-regex.js
REST API: https://chubusangaku.jp/wp-json/

**Comment by johngodley** [comment]
It looks like your plugin is corrupt:

![image](https://user-images.githubusercontent.com/1277682/102186745-f888a800-3eaa-11eb-9a31-9466671552f0.png)

You may need to reinstall it

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
