### ISSUE TITLE
"Remove all" feature

### ISSUE THREAD

**Issue by iSevenDays** [johngodley/search-regex#74]
To help track problems please follow this template. If you can provide screenshots then that will help.

We need to be able to replace found patterns with '' (empty string).

### Summary

Please add "Remove all" feature for multiple rows.

Currently, I need to select row by row, click on replace row -> remove to remove the row.

### Actual Behavior

The "Replace all" is disabled if no input is supplied.

### Steps to reproduce

1 Insert a pattern
2 See "Replace all" is disabled

### Environment

Search Regex plugin version latest of December 17, 2021.

**Comment by johngodley** [comment]
You say you want to replace with an empty string, but then you want to remove a row - I'm not sure I'm understanding fully.

To replace with an empty string you can use the dropdown on the right of the replace field.

**Comment by iSevenDays** [comment]
@johngodley thank you for the quick response.

I want to use Replace all with an empty string for removing matched patterns from the post content.

Here is a screenshot of how I apply it per-row.
https://gyazo.com/21c8218e437853e202d2a31de7473391

**Comment by iSevenDays** [comment]
Example pattern:
Match slash
(\\)+

Replace with an empty string
'' 

I need to do this for every search result.

**Comment by johngodley** [comment]
Ok, you can do the same in the global replace field.

**Comment by iSevenDays** [comment]
@johngodley could you please suggest to me how do I input empty space?

"Replace all" is grayed out, unavailable if I don't enter any text.

**Comment by johngodley** [comment]
As I said, you can use the dropdown to the right of the replace field.

**Comment by iSevenDays** [comment]
Oh now I see that option, thank you!

I don't know why I couldn't see it first time.
