### ISSUE TITLE
I can't activate in PHP 8

### ISSUE THREAD

**Issue by t-hamano** [johngodley/search-regex#79]
### Summary

'Match' is a [reserved keyword](https://github.com/php/php-src/blob/686d6c3dd4f6de64de921ba3b772c2d110d88a3e/UPGRADING#L24) in PHP 8, so I got a fatal error when I activate the plugin.

### Actual Behavior

I got error like this:

`Parse error: syntax error, unexpected token "::", expecting "(" in /var/www/html/wp-content/plugins/search-regex/models/search.php on line 322`

The reason for the error is that 'Match' is used in the class name.

### Steps to reproduce
Change the class name is needed, but 'Match' is the basic name of this plugin.
So I don't know of any other reasonable name.
Is there a better name?

**Comment by johngodley** [comment]
This will be fixed in the next version of the plugin.

**Comment by t-hamano** [comment]
Thanks for the reply.
I am looking forward to the next update.
