### ISSUE TITLE
Search Regex Error

### ISSUE THREAD

**Issue by maryannk** [johngodley/search-regex#83]
```
Plugin: 2.4.1
WordPress: 5.6.2 (single)
PHP: 7.3.27 256M 30s
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
JavaScript: https://www.m4mfoodie.mkelleyconsulting.com/wp-content/plugins/search-regex/search-regex.js
REST API: https://www.m4mfoodie.mkelleyconsulting.com/wp-json/
Query: ?page=search-regex.php&searchphrase=beef

Error: Unexpected end of JSON input (SyntaxError)
```
This issue started when I was setting options with WP Asset Cleanup. Not realizing that Search Regex uses the API, I enabled the option to remove the REST API link tag. When I realized that I needed the link tag and disabled that option, I still can't get past this Unexpected end of JSON input error. The REST API appears to be there, so I'm not sure what is causing this issue.

**Comment by johngodley** [comment]
Your REST API is returning an error:

https://www.m4mfoodie.mkelleyconsulting.com/wp-json/

**Comment by maryannk** [comment]
Thank you for your quick reply. I figured something was wrong with it, but I don't know anything about testing the REST API, I just know to see if the page loads with code. Any pointers to resources on what the error is and how to reset/fix it?

**Comment by johngodley** [comment]
It's almost certainly caused by a plugin or something like that - the error is not part of WordPress, and references http://www.facebook.com/TheHomeSchoolMom

**Comment by maryannk** [comment]
Thank you
