### ISSUE TITLE
PHP 8 compatibility error

### ISSUE THREAD

**Issue by honzigJS** [johngodley/search-regex#91]
WordPress 5.7.2
Theme: Spacious (verze 1.9.2) plugin: Search Regex (verze 2.4.1) PHP 8.0.6

ERROR
=================
row nr. 322 /www/doc/www.izoltech.cz/www/wp-content/plugins/search-regex/models/search.php error type E_PARSE. syntax error, unexpected token "::", expecting "("

**Comment by johngodley** [comment]
As detailed on the plugin page it is not yet compatible with PHP 8
