### ISSUE TITLE
Text replacements report success, but text is not changed

### ISSUE THREAD

**Issue by webmkting** [johngodley/search-regex#93]
=============================================================
#1
We're attempting to add a trailing slash to urls using the searchreplaceregex plugin.

The target text is found ok, the plugin goes through the process, yet reports zero changes made:

https://share.getcloudapp.com/GGuWAPwB

#2
We're attempting to remove a hyperlink from text, using the searchreplaceregex plugin.

The target text is found ok, the plugin goes through the process, reports that changes are made 100%, but the live pages shows no changes, even after refreshing cache.

After the change which has not been successful, the plugin then does not find the target text any longer in the DB, even though the change has not been made:

https://share.getcloudapp.com/jkuPnrZy

==========================================================

We are using the following versions:

Wordpress 5.7.2
PHP v7.4
Search Regex plugin v2.4.1
Thrive Themes and Thrive Architect

===========================================================

Please could you take a look and advise of how to fix?

Many thanks,

**Comment by johngodley** [comment]
Replied by email. Please keep issues to one place only.
