### ISSUE TITLE
[Beta 3.0] [Regex] [User experience] Too greedy? How to search & replace?

### ISSUE THREAD

**Issue by ckaden** [johngodley/search-regex#94]
What I want to do: search & replace a pattern with regex in post content only.

I just tried the 3.0 Beta for the first time and it is quite confusing. Before it was a standard behaviour that only the content is searched & replaced, quite straight forward. While it's nice that the plugin becomes more powerful, I suggest that searching & replacing restricted to the content remains the default action.

Until now I haven't managed to search & replace a pattern with regex restricted to content.

---

Regex pattern seems to work: https://nimb.ws/L0lXNH

---

**Action: Global text replace**

I have the replace field which I'm looking for, but how to restrict it to content only? "Filters: -> Content" doesn't seem to do anything.

I'm not sure what exactly is happening here. Too greedy? Lazy "?" limiter not working correcty?

https://nimb.ws/U4nhX6

---

**Action: Modify matches**

This looks a lot more what I want to do, but where's the replace field?

https://nimb.ws/c2khKA

This is the closest I managed to get to what I want to do:

https://nimb.ws/4xFpbB

Clicking on "Action -> .... -> **ADD**" sometimes lead to following error. No error when I refreshed the page and directly navigated to and clicked on ADD without doing anything else (like a search etc)
> Plugin: 3.0-beta-1
WordPress: 5.7.2 (single)
PHP: 8.0.3 256M 300s
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
JavaScript: https://staging.japan-kyoto.de/wp-content/plugins/search-regex/search-regex.js
REST API: https://staging.japan-kyoto.de/wp-json/
Query: ?page=search-regex.php&searchphrase=%3Ca.%2A%3F%5C%2Fregion%5C%2Fkyoto-stadt%5C%2F%22%3E%28.%2A%3F%29%3C%5C%2Fa%3E&searchflags%5B%5D=regex&source%5B%5D=posts&filters=%5B%7B%22type%22%3A%22posts%22%2C%22items%22%3A%5B%7B%22column%22%3A%22post_content%22%7D%5D%7D%5D&view=posts__post_content
TypeError: e.value is undefined
Tp@https://staging.japan-kyoto.de/wp-content/plugins/search-regex/search-regex.js?ver=3.0-beta-1-d67f3c48dd8700c5ab69fb974d37f5a3:2:738491
Mp@https://staging.japan-kyoto.de/wp-content/plugins/search-regex/search-regex.js?ver=3.0-beta-1-d67f3c48dd8700c5ab69fb974d37f5a3:2:742398
div
Fp@https://staging.japan-kyoto.de/wp-content/plugins/search-regex/search-regex.js?ver=3.0-beta-1-d67f3c48dd8700c5ab69fb974d37f5a3:2:742699
td
tr
ef@https://staging.japan-kyoto.de/wp-content/plugins/search-regex/search-regex.js?ver=3.0-beta-1-d67f3c48dd8700c5ab69fb974d37f5a3:2:747979
df<@https://staging.japan-kyoto.de/wp-content/plugins/search-regex/search-regex.js?ver=3.0-beta-1-d67f3c48dd8700c5ab69fb974d37f5a3:2:755518
p@https://staging.japan-kyoto.de/wp-content/plugins/search-regex/search-regex.js?ver=3.0-beta-1-d67f3c48dd8700c5ab69fb974d37f5a3:2:580131
tbody
table
Zf<@https://staging.japan-kyoto.de/wp-content/plugins/search-regex/search-regex.js?ver=3.0-beta-1-d67f3c48dd8700c5ab69fb974d37f5a3:2:777818
p@https://staging.japan-kyoto.de/wp-content/plugins/search-regex/search-regex.js?ver=3.0-beta-1-d67f3c48dd8700c5ab69fb974d37f5a3:2:580131
form
Vh@https://staging.japan-kyoto.de/wp-content/plugins/search-regex/search-regex.js?ver=3.0-beta-1-d67f3c48dd8700c5ab69fb974d37f5a3:2:832411
$h@https://staging.japan-kyoto.de/wp-content/plugins/search-regex/search-regex.js?ver=3.0-beta-1-d67f3c48dd8700c5ab69fb974d37f5a3:2:833021
ls@https://staging.japan-kyoto.de/wp-content/plugins/search-regex/search-regex.js?ver=3.0-beta-1-d67f3c48dd8700c5ab69fb974d37f5a3:2:707246
div
a@https://staging.japan-kyoto.de/wp-content/plugins/search-regex/search-regex.js?ver=3.0-beta-1-d67f3c48dd8700c5ab69fb974d37f5a3:2:679675
rm<@https://staging.japan-kyoto.de/wp-content/plugins/search-regex/search-regex.js?ver=3.0-beta-1-d67f3c48dd8700c5ab69fb974d37f5a3:2:836522
p@https://staging.japan-kyoto.de/wp-content/plugins/search-regex/search-regex.js?ver=3.0-beta-1-d67f3c48dd8700c5ab69fb974d37f5a3:2:580131
ze@https://staging.japan-kyoto.de/wp-content/plugins/search-regex/search-regex.js?ver=3.0-beta-1-d67f3c48dd8700c5ab69fb974d37f5a3:2:578196
cm

**Comment by johngodley** [comment]
> I suggest that searching & replacing restricted to the content remains the default action.

The global search/replace behaves identically to the previous version.

Note you do not need to escape the `/` - it is not a regular expression character.

I will look into the error.

**Comment by johngodley** [comment]
Beta 2 has been released which should solve a lot of these problems:

https://github.com/johngodley/search-regex/releases/tag/3.0-beta
