### ISSUE TITLE
Hyperlink replacements are not working for me (replace all)

### ISSUE THREAD

**Issue by m0nty3** [johngodley/search-regex#96]
Hi!
I'm using the plugin and if I don't use regular expressions it works fine for me.

The problem is when I try to use regular expressions to do replacements. For example, I try to replace the content of a hyperlink and when I hit Search I have no problems, but when I try to do replacements the plugin does nothing. It just tells me that the replacements have been made but no row has been modified.

For what is this?
Thanks a lot.

### Environment

Browser: Chrome
Wordpress: 5.4

**Comment by johngodley** [comment]
Can you try the 3.0 beta?

https://github.com/johngodley/search-regex/releases/tag/3.0-beta
